name: Publish to GitHub Pages

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install minijinja-cli
        run: |
          curl -sSfL https://github.com/mitsuhiko/minijinja/releases/latest/download/minijinja-cli-installer.sh -o install.sh
          sh install.sh
          echo "Hello {{ name }}" | minijinja-cli - -Dname=World

      - name: Get latest data
        run: |
          wget https://data.baemillion.com/latest.tar.gz
          tar -xvzf latest.tar.gz
          echo "Contents of release.txt"
          cat release.txt

      - name: Generate static site
        id: generation
        run: |
          ./render.sh
          # Print the contents of the newly generated dist/ directory
          echo "The following files have been generated:"
          tree ./dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          folder: dist/
          force: false
          clean-exclude: pr-preview/
